```{r}
getwd()
```
```{r}
setwd("C:/Users/hp/Desktop/Ph.D.Classes/MoD/Assignments/AsignmentI/Data")
```

```{r}
TripData_202101_1 <- read.csv("202101-capitalbikeshare-tripdata_1.csv")
```

```{r}
TripData_Cleaned_1_202101 <- TripData_202101_1[! (TripData_202101_1$start_day == "Saturday" | TripData_202101_1$start_day == "Sunday"), ]
```

```{r}
write.csv(TripData_Cleaned_1_202101, file = "C:/Users/hp/Desktop/Ph.D.Classes/MoD/Assignments/AsignmentI/Data/TripData_Cleaned_1_202101.csv")
```

```{r}
TripData_Cleaned_2_202101 <- read.csv("TripData_Cleaned_2_202101.csv")
```

```{r}
TripData_Cleaned_2_202101
```
```{r}
Monday_TripData_Cleaned_2_202101 <- TripData_Cleaned_2_202101[with(TripData_Cleaned_2_202101, which(start_day == "Monday")), ]
```

```{r}
Monday_TripData_Cleaned_2_202101
```
```{r}
write.csv(Monday_TripData_Cleaned_2_202101, file = "C:/Users/hp/Desktop/Ph.D.Classes/MoD/Assignments/AsignmentI/Data/Monday_TripData_Cleaned_2_202101.csv")
```
```{r}
Monday_TripData_Cleaned_2_202101 <- read.csv("Monday_TripData_Cleaned_2_202101.csv")
Monday_TripData_Cleaned_2_202101
```
```{r}
Monday_TripData_Cleaned_2_202101 <- read.csv("Monday_TripData_Cleaned_2_202101.csv")
Monday_TripData_Cleaned_2_202101
```
```{r}
Monday <- aggregate(trip ~ start_time, data= Monday_TripData_Cleaned_2_202101, sum)

write.csv(Monday, file = "C:/Users/hp/Desktop/Ph.D.Classes/MoD/Assignments/AsignmentI/Data/Monday.csv")
Monday
```
```{r}
Tuesday_TripData_Cleaned_2_202101 <- TripData_Cleaned_2_202101[with(TripData_Cleaned_2_202101, which(start_day == "Tuesday")), ]
Tuesday_TripData_Cleaned_2_202101
```

```{r}
write.csv(Tuesday_TripData_Cleaned_2_202101, file = "C:/Users/hp/Desktop/Ph.D.Classes/MoD/Assignments/AsignmentI/Data/Tuesday_TripData_Cleaned_2_202101.csv")
```


```{r}
Tuesday_TripData_Cleaned_2_202101 <- read.csv("Tuesday_TripData_Cleaned_2_202101.csv")
Tuesday_TripData_Cleaned_2_202101
```

```{r}
write.csv("Tuesday_TripData_Cleaned_2_202101.csv", file = "C:/Users/hp/Desktop/Ph.D.Classes/MoD/Assignments/AsignmentI/Data/Tuesday_TripData_Cleaned_2_202101.csv")
```

```{r}
Tuesday_TripData_Cleaned_2_202101 <- read.csv("Tuesday_TripData_Cleaned_2_202101.csv")
Tuesday_TripData_Cleaned_2_202101
```
```{r}
Tuesday <- aggregate(trip ~ start_time, data= Tuesday_TripData_Cleaned_2_202101, sum)

write.csv(Tuesday, file = "C:/Users/hp/Desktop/Ph.D.Classes/MoD/Assignments/AsignmentI/Data/Tuesday.csv")
Tuesday
```
```{r}
Wednesday_TripData_Cleaned_2_202101 <- TripData_Cleaned_2_202101[with(TripData_Cleaned_2_202101, which(start_day == "Wednesday")), ]
Wednesday_TripData_Cleaned_2_202101

Thursday_TripData_Cleaned_2_202101 <- TripData_Cleaned_2_202101[with(TripData_Cleaned_2_202101, which(start_day == "Thursday")), ]
Thursday_TripData_Cleaned_2_202101

Friday_TripData_Cleaned_2_202101 <- TripData_Cleaned_2_202101[with(TripData_Cleaned_2_202101, which(start_day == "Friday")), ]
Friday_TripData_Cleaned_2_202101
```
```{r}
write.csv(Wednesday_TripData_Cleaned_2_202101, file = "C:/Users/hp/Desktop/Ph.D.Classes/MoD/Assignments/AsignmentI/Data/Wednesday_TripData_Cleaned_2_202101.csv")

write.csv(Thursday_TripData_Cleaned_2_202101, file = "C:/Users/hp/Desktop/Ph.D.Classes/MoD/Assignments/AsignmentI/Data/Thursday_TripData_Cleaned_2_202101.csv")

write.csv(Friday_TripData_Cleaned_2_202101, file = "C:/Users/hp/Desktop/Ph.D.Classes/MoD/Assignments/AsignmentI/Data/Friday_TripData_Cleaned_2_202101.csv")
```


```{r}
Wednesday_TripData_Cleaned_2_202101 <- read.csv("Wednesday_TripData_Cleaned_2_202101.csv")
Wednesday_TripData_Cleaned_2_202101

Thursday_TripData_Cleaned_2_202101 <- read.csv("Thursday_TripData_Cleaned_2_202101.csv")
Thursday_TripData_Cleaned_2_202101

Friday_TripData_Cleaned_2_202101 <- read.csv("Friday_TripData_Cleaned_2_202101.csv")
Friday_TripData_Cleaned_2_202101
```

```{r}
Wednesday <- aggregate(trip ~ start_time, data= Wednesday_TripData_Cleaned_2_202101, sum)

write.csv(Wednesday, file = "C:/Users/hp/Desktop/Ph.D.Classes/MoD/Assignments/AsignmentI/Data/Wednesday.csv")
Wednesday

Thursday <- aggregate(trip ~ start_time, data= Thursday_TripData_Cleaned_2_202101, sum)

write.csv(Thursday, file = "C:/Users/hp/Desktop/Ph.D.Classes/MoD/Assignments/AsignmentI/Data/Thursday.csv")
Thursday

Friday <- aggregate(trip ~ start_time, data= Friday_TripData_Cleaned_2_202101, sum)

write.csv(Friday, file = "C:/Users/hp/Desktop/Ph.D.Classes/MoD/Assignments/AsignmentI/Data/Friday.csv")
Friday
```
